---
extends: airbnb
parser: babel-eslint
env:
  browser: true
  node: true
rules:
  arrow-parens:
  - 2
  - as-needed
  consistent-return: 0
  import/first: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/order:
  - 2
  - groups:
    - builtin
    - external
    - sibling
    - parent
    - index
    newlines-between: always
  import/prefer-default-export: 0
  indent:
  - 2
  - tab
  no-console:
  - 2
  - allow:
    - info
    - error
  no-extra-parens: 0
  no-multiple-empty-lines:
  - 2
  - max: 1
    maxBOF: 0
    maxEOF: 0
  no-param-reassign: 0
  no-tabs: 0
  react/jsx-indent:
  - 2
  - tab
  react/jsx-indent-props:
  - 2
  - tab
