version: 2

jobs:
  build:
    docker:
    - image: node:8.4.0

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
    - run: yarn bootstrap
    - save_cache:
        key: v1-dependencies-{{ checksum "yarn.lock" }}
        paths:
        - node_modules
    - run: yarn build
    - run: yarn lint
